### ISSUE TITLE
Missing access

### ISSUE THREAD

**Issue by notuniq** [KartikeSingh/discord-embed-builder#2]
HELP!!!
`[nodemon] starting `ts-node src/index.ts`
gg
client is up and running!
DiscordAPIError[50001]: Missing Access
    at SequentialHandler.runRequest (C:\Users\jenya\Desktop\discord-embed-builder-new\backend\node_modules\@discordjs\rest\dist\lib\handlers\lib\handlers\SequentialHandler.ts:215:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (C:\Users\jenya\Desktop\discord-embed-builder-new\backend\node_modules\@discordjs\rest\dist\lib\handlers\lib\handlers\SequentialHandler.ts:111:11) {
  rawError: { message: 'Missing Access', code: 50001 },
  code: 50001,
  status: 403,
  method: 'put',
  url: 'https://discord.com/api/v9/applications/903368944868532294/guilds/732883841395720213/commands'
}
[nodemon] app crashed - waiting for file changes before starting...`

**Comment by KartikeSingh** [comment]
I am sorry i didn't saw this issue, probably you fixed it but just for surety I will tell you the fix
and the fix is :
1. kick your bot from the server where you are adding the slash command
2. Re invite your bot with applications.commands scope 
@evg3n1y-btw
